spring:
  application:
    name: organize_it_backend
  data:
    mongodb:
      uri: mongodb+srv://jashwanthn066:HVnToAWSgq9ugqq4@organizeit.a1tsf.mongodb.net/organizeit?retryWrites=true&w=majority
      database: organize_it
server:
  port: 8080
